# permissions for end users to view featureflagrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: featureflagrules-viewer-role
rules:
- apiGroups:
  - cache.openfeature.dev
  resources:
  - featureflagrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.openfeature.dev
  resources:
  - featureflagrules/status
  verbs:
  - get
