# permissions for end users to edit featureflagrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: featureflagrules-editor-role
rules:
- apiGroups:
  - cache.openfeature.dev
  resources:
  - featureflagrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.openfeature.dev
  resources:
  - featureflagrules/status
  verbs:
  - get
