---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - openfeature.dev
  resources:
  - featureflagrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openfeature.dev
  resources:
  - featureflagrules/finalizers
  verbs:
  - update
- apiGroups:
  - openfeature.dev
  resources:
  - featureflagrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openfeature.dev
  resources:
  - featureflags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openfeature.dev
  resources:
  - featureflags/finalizers
  verbs:
  - update
- apiGroups:
  - openfeature.dev
  resources:
  - featureflags/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openfeature.dev
  resources:
  - openfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openfeature.dev
  resources:
  - openfeatures/finalizers
  verbs:
  - update
- apiGroups:
  - openfeature.dev
  resources:
  - openfeatures/status
  verbs:
  - get
  - patch
  - update
